name: pemrograman_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.5.3
  pdf: ^3.10.6
  printing: ^5.11.2
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/IMG_0752.JPG