// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqAGoLWXW6skxwRKL1xFjFpogMHzgwkM',
    appId: '1:587874062713:web:41f89312cd855754efdfa8',
    messagingSenderId: '587874062713',
    projectId: 'expense-manager-2025-1d1db',
    authDomain: 'expense-manager-2025-1d1db.firebaseapp.com',
    storageBucket: 'expense-manager-2025-1d1db.firebasestorage.app',
    measurementId: 'G-X14HLTHXCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiKc0xjZhKBuQc2CogKKlOfP7ZX6opYM',
    appId: '1:587874062713:android:51849ea9ebe76a62efdfa8',
    messagingSenderId: '587874062713',
    projectId: 'expense-manager-2025-1d1db',
    storageBucket: 'expense-manager-2025-1d1db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScpsGrkOpP11w2Grx5COYkJGHWjYE1rI',
    appId: '1:587874062713:ios:47d5c5742c640005efdfa8',
    messagingSenderId: '587874062713',
    projectId: 'expense-manager-2025-1d1db',
    storageBucket: 'expense-manager-2025-1d1db.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDScpsGrkOpP11w2Grx5COYkJGHWjYE1rI',
    appId: '1:587874062713:ios:47d5c5742c640005efdfa8',
    messagingSenderId: '587874062713',
    projectId: 'expense-manager-2025-1d1db',
    storageBucket: 'expense-manager-2025-1d1db.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwqAGoLWXW6skxwRKL1xFjFpogMHzgwkM',
    appId: '1:587874062713:web:222af591718ae1f2efdfa8',
    messagingSenderId: '587874062713',
    projectId: 'expense-manager-2025-1d1db',
    authDomain: 'expense-manager-2025-1d1db.firebaseapp.com',
    storageBucket: 'expense-manager-2025-1d1db.firebasestorage.app',
    measurementId: 'G-LM34Z7ZWH6',
  );
}
